language: php

php:
  - 7.1
  - 7.2
  - 7.3

# omitting "script:" will default to phpunit

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

script:
  - ./vendor/bin/phpunit 
