language: php

php:
  - 7.1
  - 7.2
  - 7.3


install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit.xml --coverage-text

